<p>Select the adjectives!</p>

<table class="table-auto">
	<tbody class="adjectives">
        <tr>
			<td>able</td>
			<td>accepting</td>
			<td>adaptable</td>
			<td>bold</td>
			<td>brave</td>
		</tr>
		<tr>
			<td>calm</td>
			<td>caring</td>
			<td>cheerful</td>
			<td>clever</td>
			<td>complex</td>
		</tr>
		<tr>
			<td>confident</td>
			<td>dependable</td>
			<td>dignified</td>
			<td>energetic</td>
			<td>extroverted</td>
		</tr>
		<tr>
			<td>friendly</td>
			<td>giving</td>
			<td>happy</td>
			<td>helpful</td>
			<td>idealistic</td>
		</tr>
		<tr
			><td>independent</td>
			<td>ingenious</td>
			<td>intelligent</td>
			<td>introverted</td>
			<td>kind</td>
		</tr>
		<tr>
			<td>knowledgeable</td>
			<td>logical</td>
			<td>loving</td>
			<td>mature</td>
			<td>modest</td>
		</tr>
		<tr>
			<td>nervous</td>
			<td>observant</td>
			<td>organised</td>
			<td>patient</td>
			<td>powerful</td>
		</tr>
		<tr>
			<td>proud</td>
			<td>quiet</td>
			<td>reflective</td>
			<td>relaxed</td>
			<td>religious</td>
		</tr>
		<tr>
			<td>responsive</td>
			<td>searching</td>
			<td>self-assertive</td>
			<td>self-conscious</td>
			<td>sensible</td>
		</tr>
		<tr>
			<td>sentimental</td>
			<td>shy</td>
			<td>silly</td>
			<td>spontaneous</td>
			<td>sympathetic</td>
		</tr>
		<tr>
			<td>tense</td>
			<td>trustworthy</td>
			<td>warm</td>
			<td>wise</td>
			<td>witty</td>
		</tr>
	</tbody>
</table>
